### ISSUE TITLE
Missing function

### ISSUE THREAD

**Issue by bkgithubbk** [ur-whitelab/wazy#20]
Hi Andrew and Ziyue,

Many thanks for fixing the previous issue.
Function build_e2e used in "Bayesian-Opt Sine.ipynb", "BiLSTM.ipynb" and "mlp.ipynb" is missing.
Would you mind committing that to the repo?

Regards,
Babak

**Comment by ziyueyang37** [comment]
Hi Babak,

Since "Bayesian-Opt Sine.ipynb", "BiLSTM.ipynb" and "mlp.ipynb" are not used anywhere in the paper, we deleted those notebooks. Thanks! 

Best,
Ziyue
