### ISSUE TITLE
MSA variable parsing/assignment fails

### ISSUE THREAD

**Issue by janerallison** [ur-whitelab/wazy#29]
When running the Colab notebook with the default settings (i.e., as provided), the MSA options code box results in "Could not parse variable and value from ""unpaired+paired"". Expected the line to start with a variable assignment." (but still appears to have run).

Occurs for all MMSeqs2 options.

**Comment by ziyueyang37** [comment]
Seems like the syntax has changed. Just need to delete the '(' and ')'. Changes pushed to master
