### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by janerallison** [ur-whitelab/wazy#30]
When running with the default options (i.e., as provided), the Install dependencies code box fails with the following error:

ERROR: Cannot install jax[cuda11-cudnn805]==0.3.10, jax[cuda11-cudnn805]==0.3.11, jax[cuda11-cudnn805]==0.3.12, jax[cuda11-cudnn805]==0.3.13, jax[cuda11-cudnn805]==0.3.14, jax[cuda11-cudnn805]==0.3.15, jax[cuda11-cudnn805]==0.3.16, jax[cuda11-cudnn805]==0.3.17, jax[cuda11-cudnn805]==0.3.18, jax[cuda11-cudnn805]==0.3.19, jax[cuda11-cudnn805]==0.3.20, jax[cuda11-cudnn805]==0.3.21, jax[cuda11-cudnn805]==0.3.22, jax[cuda11-cudnn805]==0.3.23, jax[cuda11-cudnn805]==0.3.24, jax[cuda11-cudnn805]==0.3.25, jax[cuda11-cudnn805]==0.3.8 and jax[cuda11-cudnn805]==0.3.9 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by ziyueyang37** [comment]
fixed in master
