### ISSUE TITLE
Error executing 'Install Dependencies' cell

### ISSUE THREAD

**Issue by jalegriolouro** [ur-whitelab/wazy#33]
I tried running the wazy+alphafold notebook with the following input parameters: protein sequence, starting binder, high quality box checked, template mode pdb70, 6 recycles. However, the results were not downloaded. I then removed pop-up blockers and restarted the job several times, always with some error while installing dependencies.

Please find the error attached.

Thank you! 

[wazy_install_dependencies_error.txt](https://github.com/ur-whitelab/wazy/files/11391652/wazy_install_dependencies_error.txt)

**Comment by ziyueyang37** [comment]
solved
