### ISSUE TITLE
Not able to find results.zip

### ISSUE THREAD

**Issue by jalegriolouro** [ur-whitelab/wazy#35]
Hi, 

Thank you for solving the previous issue and thank you in advance for this one:)

I ran your notebook with the following parameters: protein sequence, starting binder, high quality box checked, template mode pdb70, 6 recycles. However, the results were not downloaded and are not in sample_data (please check attached screenshots).

I tried to re-execute the cell and got an error about invalid msa input (I forgot to screenshot that one).

I also noticed that the plot results cell failed to execute during the run, although it seemed fine at the end (I left the job running overnight).

![Untitled](https://github.com/ur-whitelab/wazy/assets/126015023/af2f8c87-71eb-4337-a57c-74a02be76297)

![Untitled1](https://github.com/ur-whitelab/wazy/assets/126015023/1e5a559d-c20d-4784-b2c9-ab3ffc093ee0)

Cheers,
Jaime

**Comment by ziyueyang37** [comment]
fixed in the latest change
